# Generated by Django 3.2 on 2022-07-12 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_detail',
            name='sent_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
