# Generated by Django 3.2 on 2022-07-12 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0002_sms_detail_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciepient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
