# Generated by Django 3.2 on 2022-07-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0003_email_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_detail',
            name='Content',
            field=models.TextField(),
        ),
    ]
