# Generated by Django 3.2 on 2022-07-13 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0004_alter_email_detail_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watsapp_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=10)),
                ('Content', models.CharField(max_length=200)),
                ('msgid', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
