# Generated by Django 3.2 on 2022-07-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0005_watsapp_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_detail',
            name='Countrycode',
            field=models.CharField(blank=True, default=91, max_length=6),
        ),
    ]
