# Generated by Django 3.2 on 2022-07-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0006_sms_detail_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='watsapp_detail',
            name='Countrycode',
            field=models.CharField(default=91, max_length=6),
        ),
        migrations.AlterField(
            model_name='sms_detail',
            name='Countrycode',
            field=models.CharField(default=91, max_length=6),
        ),
    ]
