# Generated by Django 3.2 on 2022-07-26 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0007_auto_20220714_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='call_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Countrycode', models.CharField(default=91, max_length=6)),
                ('Number', models.CharField(max_length=10)),
                ('Content', models.CharField(max_length=200)),
                ('msgid', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
