# Generated by Django 3.2 on 2022-07-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='charid',
            new_name='called_from',
        ),
        migrations.RemoveField(
            model_name='chatresponse',
            name='chatbot_response',
        ),
        migrations.AddField(
            model_name='history',
            name='chatid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='chat_history',
            field=models.ManyToManyField(blank=True, null=True, to='call.chatresponse'),
        ),
    ]
