# Generated by Django 3.2 on 2022-07-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_auto_20220727_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='chat_history',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='call.chatresponse'),
        ),
    ]
