# Generated by Django 3.2 on 2022-07-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_alter_history_chat_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatresponse',
            name='chatbot_json',
        ),
    ]
