# Generated by Django 3.2 on 2022-07-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_remove_chatresponse_chatbot_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatresponse',
            name='chatbot_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
